package storage

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// ErrAttachmentNotFound is the one answer to every way an attachment id can
// fail to be claimable: no such file, another channel's, another person's,
// or one already attached to a message. The contract names a single code
// (attachment_not_found) for all four on purpose — a caller that could tell
// them apart could probe for other people's uploads by id.
var ErrAttachmentNotFound = errors.New("storage: attachment not found")

// ErrEmptyMessage is the "text or files, never neither" refusal. The
// database allows empty content on a live message since migration 0007 —
// an image with no caption is an ordinary message — so the rule lives here,
// where it is atomic with the claim that makes an empty message legal.
var ErrEmptyMessage = errors.New("storage: message has neither text nor attachments")

// Attachment is a row of the attachments table: the metadata of one uploaded
// file. The bytes live on the filesystem under a path derived from ID alone
// (internal/blobstore); nothing here ever becomes part of a path.
//
// MessageID is nil between upload and send. Width, Height and HasThumbnail
// are set only for images, and only after the bytes proved to be the image
// they claimed (ADR 003).
type Attachment struct {
	ID           uuid.UUID
	ChannelID    uuid.UUID
	UploaderID   uuid.UUID
	MessageID    *uuid.UUID
	Filename     string
	ContentType  string
	SizeBytes    int64
	Width        *int
	Height       *int
	HasThumbnail bool
	CreatedAt    time.Time
}

// NewAttachment carries the fields for recording an upload. The blob is
// already on disk by the time this is called: a row without its bytes would
// render a broken card, while bytes without a row are just an orphan the
// sweep collects.
type NewAttachment struct {
	// ID is generated by the caller rather than by the database, because the
	// blob has to be written under it before there is any row to read one
	// from. It is the server's own UUID either way — nothing a client sends
	// reaches it.
	ID           uuid.UUID
	ChannelID    uuid.UUID
	UploaderID   uuid.UUID
	Filename     string
	ContentType  string
	SizeBytes    int64
	Width        *int
	Height       *int
	HasThumbnail bool
}

// attachmentColumns is the canonical column list every attachment query
// selects, in the order scanAttachment expects.
const attachmentColumns = `id, channel_id, uploader_id, message_id, filename, content_type, size_bytes, width, height, has_thumbnail, created_at`

const insertAttachmentQuery = `INSERT INTO attachments
	    (id, channel_id, uploader_id, filename, content_type, size_bytes, width, height, has_thumbnail)
	VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
	RETURNING ` + attachmentColumns

// claimAttachmentsQuery attaches this author's unattached uploads in this
// channel to the message just inserted, and returns the rows it claimed.
//
// The four conditions are one filter rather than four answers: an id that
// fails any of them simply does not come back, the returned count falls
// short of the asked-for count, and the caller fails the whole send with the
// contract's single attachment_not_found.
//
// message_position is the id's index in the list the sender gave, which is
// the order their cards render in (migration 0020). array_position is 1-based,
// hence the -1, and it cannot come back NULL: the same array is this
// statement's own filter, so every row it updates is one the array contains.
//
// The sub-select takes the row locks explicitly, in id order. That order is
// the entire reason two concurrent sends claiming overlapping ids cannot
// deadlock: without it PostgreSQL would lock the rows in whatever order the
// scan produced, and two senders could take the same two rows in opposite
// orders. Under READ COMMITTED the loser of a race re-evaluates the WHERE
// against the updated row, finds message_id no longer NULL, and drops it
// from the result — which is exactly the count mismatch the caller refuses on.
const claimAttachmentsQuery = `UPDATE attachments a
	SET message_id = $1,
	    message_position = array_position($2::uuid[], a.id) - 1
	FROM (
	    SELECT id FROM attachments
	    WHERE id = ANY($2::uuid[])
	      AND channel_id = $3
	      AND uploader_id = $4
	      AND message_id IS NULL
	    ORDER BY id
	    FOR UPDATE
	) locked
	WHERE a.id = locked.id
	RETURNING a.id, a.channel_id, a.uploader_id, a.message_id, a.filename,
	          a.content_type, a.size_bytes, a.width, a.height, a.has_thumbnail, a.created_at`

// attachmentsByMessagesQuery reads the cards of a whole page of history in
// one round trip. A page of fifty messages must not cost fifty queries.
//
// The order is the sender's, per message. No tiebreak follows it and none is
// needed: 0020's attachments_message_order_idx is UNIQUE on exactly this
// pair, so two cards of one message cannot share a position. The leading
// message_id is not for the caller — the rows are grouped by it in Go — but
// for that index, which then answers the filter and the sort together.
const attachmentsByMessagesQuery = `SELECT ` + attachmentColumns + `
	FROM attachments
	WHERE message_id = ANY($1::uuid[])
	ORDER BY message_id, message_position`

// sweepOrphansQuery deletes the uploads that never became a message and
// hands back their ids so the caller can delete the blobs. The row goes
// first: a row without bytes is a broken card, a blob without a row is
// disk the next sweep cannot even find.
const sweepOrphansQuery = `DELETE FROM attachments
	WHERE message_id IS NULL AND created_at < $1
	RETURNING id`

// CreateAttachment records one uploaded file against its channel and
// uploader, unattached to any message.
//
// A channel that went away between the membership check and this call is
// ErrNotFound, not a constraint error — the same translation every messaging
// write does.
func (s *Store) CreateAttachment(ctx context.Context, na NewAttachment) (Attachment, error) {
	row := s.pool.QueryRow(ctx, insertAttachmentQuery,
		na.ID, na.ChannelID, na.UploaderID, na.Filename, na.ContentType, na.SizeBytes,
		na.Width, na.Height, na.HasThumbnail)
	att, err := scanAttachment(row)
	if err != nil {
		return Attachment{}, fmt.Errorf("create attachment: %w", mapMissingReference(err))
	}
	return att, nil
}

// AttachmentByID reads one attachment by id alone, or ErrNotFound.
//
// It is the one read that is not scoped to a channel, because it serves the
// cookie-less files origin, where there is no caller to scope it to:
// entitlement was settled when the URL was signed, and the signature is the
// credential (ADR 003). Every other read of an attachment goes through the
// message that carries it.
func (s *Store) AttachmentByID(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := s.pool.QueryRow(ctx, `SELECT `+attachmentColumns+` FROM attachments WHERE id = $1`, id)
	att, err := scanAttachment(row)
	if err != nil {
		return Attachment{}, fmt.Errorf("attachment by id: %w", err)
	}
	return att, nil
}

// AttachmentsByMessages reads the attachments of many messages at once,
// grouped by message id. It is how a page of history gets its file cards:
// one query for the page, never one per message.
//
// Access control is not its job — the caller has already decided who may see
// the messages it is asked about.
func (s *Store) AttachmentsByMessages(ctx context.Context, messageIDs []uuid.UUID) (map[uuid.UUID][]Attachment, error) {
	byMessage := map[uuid.UUID][]Attachment{}
	if len(messageIDs) == 0 {
		return byMessage, nil
	}

	rows, err := s.pool.Query(ctx, attachmentsByMessagesQuery, messageIDs)
	if err != nil {
		return nil, fmt.Errorf("attachments by messages: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		att, scanErr := scanAttachment(rows)
		if scanErr != nil {
			return nil, fmt.Errorf("attachments by messages: %w", scanErr)
		}
		// message_id is never NULL here: the query filters on it.
		byMessage[*att.MessageID] = append(byMessage[*att.MessageID], att)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("attachments by messages: %w", err)
	}
	return byMessage, nil
}

// SweepOrphanAttachments deletes the uploads older than age that never
// reached a message, and returns their ids so the caller can delete the
// blobs behind them.
//
// An abandoned composer therefore costs a day of disk rather than forever
// (ADR 003). The returned ids are the caller's to act on: a blob left behind
// by a failed delete is disk nothing will ever reclaim, so the caller logs
// rather than swallows.
func (s *Store) SweepOrphanAttachments(ctx context.Context, age time.Duration) ([]uuid.UUID, error) {
	rows, err := s.pool.Query(ctx, sweepOrphansQuery, time.Now().Add(-age))
	if err != nil {
		return nil, fmt.Errorf("sweep orphan attachments: %w", err)
	}
	defer rows.Close()

	ids := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if scanErr := rows.Scan(&id); scanErr != nil {
			return nil, fmt.Errorf("sweep orphan attachments: %w", scanErr)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("sweep orphan attachments: %w", err)
	}
	return ids, nil
}

// loadMessageCards fills everything a client-serving read owes beyond the
// message rows themselves — the file cards and the link-preview card — each
// as one batched query for the whole page, never one per message.
func (s *Store) loadMessageCards(ctx context.Context, msgs []Message) error {
	if err := s.loadAttachments(ctx, msgs); err != nil {
		return err
	}
	ids := make([]uuid.UUID, len(msgs))
	for i := range msgs {
		ids[i] = msgs[i].ID
	}
	previews, err := s.LinkPreviewsByMessage(ctx, ids)
	if err != nil {
		return err
	}
	for i := range msgs {
		if preview, ok := previews[msgs[i].ID]; ok {
			p := preview
			msgs[i].Preview = &p
		}
	}
	return nil
}

// loadAttachments fills in the Attachments of every message in msgs, in one
// query for the whole slice.
func (s *Store) loadAttachments(ctx context.Context, msgs []Message) error {
	if len(msgs) == 0 {
		return nil
	}
	ids := make([]uuid.UUID, len(msgs))
	for i, m := range msgs {
		ids[i] = m.ID
	}

	byMessage, err := s.AttachmentsByMessages(ctx, ids)
	if err != nil {
		return err
	}
	for i := range msgs {
		msgs[i].Attachments = byMessage[msgs[i].ID]
	}
	return nil
}

// scanAttachment scans one attachmentColumns row. pgx.ErrNoRows becomes
// ErrNotFound.
func scanAttachment(row pgx.Row) (Attachment, error) {
	var a Attachment
	err := row.Scan(
		&a.ID, &a.ChannelID, &a.UploaderID, &a.MessageID, &a.Filename,
		&a.ContentType, &a.SizeBytes, &a.Width, &a.Height, &a.HasThumbnail, &a.CreatedAt,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return Attachment{}, ErrNotFound
	}
	if err != nil {
		return Attachment{}, err
	}
	return a, nil
}
