/**
 * Lifecycle of the stack the end-to-end suite drives.
 *
 * The suite talks to the real deployment: Caddy terminating TLS in front of
 * the Go binary that carries the web bundle, with a real PostgreSQL behind
 * it — the same `deploy/docker-compose.yml` an operator runs, plus the port
 * overlay in webapp/e2e/docker-compose.e2e.yml. Nothing is mocked; MSW is
 * what the Vitest unit tests already use, and re-testing it here would prove
 * nothing about the shipped product.
 *
 * Two things keep this away from a developer's own instance, which may be
 * running on the same machine with volumes full of real data:
 *
 *   - a separate project name (hamlaneh-e2e), which namespaces containers
 *     AND volumes, so `down -v` here can never delete theirs;
 *   - a generated --env-file, so deploy/.env is never read and their
 *     database password is never involved.
 */
import { randomBytes } from "node:crypto";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { spawnSync } from "node:child_process";
import tls from "node:tls";
import { fileURLToPath } from "node:url";

/** webapp/e2e/support -> repository root. */
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

const PROJECT_NAME = "hamlaneh-e2e";
const STATE_DIR = path.join(REPO_ROOT, "webapp", "e2e", ".stack");
const ENV_FILE = path.join(STATE_DIR, "e2e.env");
const STATE_FILE = path.join(STATE_DIR, "stack.json");

const COMPOSE_FILES = [
  path.join(REPO_ROOT, "deploy", "docker-compose.yml"),
  path.join(REPO_ROOT, "webapp", "e2e", "docker-compose.e2e.yml"),
];

/** Off 443 so a Hamlaneh instance already running on this machine keeps it. */
const HTTPS_PORT = Number(process.env.HAMLANEH_E2E_HTTPS_PORT ?? "8443");

/** Caddy issues for "localhost" from its internal CA; see assertServedByCaddy. */
const CADDY_INTERNAL_ISSUER = "Caddy Local Authority";

const STARTUP_TIMEOUT_MS = 300_000;
const POLL_INTERVAL_MS = 2_000;

/** What global setup hands the workers. */
export interface StackState {
  baseURL: string;
  /** The bootstrapped first admin, after its forced password change. */
  admin: { username: string; password: string };
}

/** A throwaway secret for one run. Never a fixed value — CLAUDE.md, Git rules. */
function secret(): string {
  return randomBytes(24).toString("base64url");
}

function compose(args: string[], options: { check: boolean } = { check: true }): string {
  const result = spawnSync(
    "docker",
    [
      "compose",
      "-p",
      PROJECT_NAME,
      ...COMPOSE_FILES.flatMap((file) => ["-f", file]),
      "--env-file",
      ENV_FILE,
      ...args,
    ],
    { encoding: "utf8", cwd: REPO_ROOT },
  );
  if (result.error !== undefined) {
    throw new Error(`docker compose ${args.join(" ")} could not be run: ${result.error.message}`);
  }
  const output = `${result.stdout}${result.stderr}`;
  if (options.check && result.status !== 0) {
    throw new Error(`docker compose ${args.join(" ")} failed (exit ${String(result.status)})\n${output}`);
  }
  return output;
}

/**
 * Writes the environment the stack starts with. The admin bootstrap
 * variables are the supported way to get an account on a fresh instance
 * (server/internal/bootstrap): the server reads them only while the users
 * table is empty, and the account it creates must change its password at
 * first sign-in — which is itself one of the flows under test.
 *
 * SMTP points at a reserved .invalid host on purpose. Password reset is only
 * offered when a transport is configured, so the "Forgot password?" link
 * exists only with these set; delivery itself happens off the response path
 * (the request answers 202 either way), so a host that cannot resolve is
 * enough to exercise everything the suite asserts, with no mail server to
 * run or clean up.
 */
function writeEnvFile(adminPassword: string): void {
  mkdirSync(STATE_DIR, { recursive: true });
  const lines = [
    "# Generated by webapp/e2e/support/stack.ts. Throwaway; never committed.",
    "HAMLANEH_DOMAIN=localhost",
    `HAMLANEH_E2E_HTTPS_PORT=${String(HTTPS_PORT)}`,
    `POSTGRES_PASSWORD=${secret()}`,
    // The files origin refuses to boot without a signing key, exactly as a
    // real install would; the throwaway stack generates one the same way.
    `HAMLANEH_FILE_URL_KEY=${secret()}`,
    "HAMLANEH_ADMIN_USERNAME=e2eadmin",
    `HAMLANEH_ADMIN_PASSWORD=${adminPassword}`,
    "HAMLANEH_ADMIN_LOCALE=en",
    `HAMLANEH_PUBLIC_URL=https://localhost:${String(HTTPS_PORT)}`,
    "HAMLANEH_SMTP_HOST=smtp.e2e.invalid",
    "HAMLANEH_SMTP_FROM=hamlaneh@e2e.invalid",
    "HAMLANEH_SMTP_FROM_NAME=Hamlaneh E2E",
    "",
  ];
  writeFileSync(ENV_FILE, lines.join("\n"), { encoding: "utf8", mode: 0o600 });
}

interface ComposeServiceState {
  Service?: string;
  State?: string;
  Health?: string;
}

/**
 * `docker compose ps --format json` prints a JSON array in some versions and
 * one object per line in others; both forms are in the wild and which one a
 * runner has is not ours to choose, so both are read.
 */
function parseComposePs(raw: string): ComposeServiceState[] {
  const trimmed = raw.trim();
  if (trimmed.startsWith("[")) {
    return JSON.parse(trimmed) as ComposeServiceState[];
  }
  return trimmed
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("{"))
    .map((line) => JSON.parse(line) as ComposeServiceState);
}

/** Blocks until every service is running and every health check is green. */
async function waitForHealthy(): Promise<void> {
  const deadline = Date.now() + STARTUP_TIMEOUT_MS;
  for (;;) {
    const services = parseComposePs(compose(["ps", "--all", "--format", "json"], { check: false }));

    const dead = services.filter((s) => s.State === "exited" || s.State === "dead");
    if (dead.length > 0) {
      throw new Error(`e2e stack: service exited during startup\n${compose(["ps", "--all"])}`);
    }
    const pending = services.filter(
      (s) => s.State !== "running" || (s.Health !== undefined && s.Health !== "" && s.Health !== "healthy"),
    );
    if (services.length > 0 && pending.length === 0) {
      return;
    }
    if (Date.now() > deadline) {
      const state = services
        .map((s) => `${s.Service ?? "?"}=${s.State ?? "?"}/${s.Health ?? "-"}`)
        .join(" ");
      throw new Error(`e2e stack: timed out waiting for services to become healthy (${state})`);
    }
    await new Promise((resolve) => setTimeout(resolve, POLL_INTERVAL_MS));
  }
}

/**
 * Proves the suite is really talking to Caddy over TLS.
 *
 * The browser contexts run with ignoreHTTPSErrors, and they have to: with
 * HAMLANEH_DOMAIN=localhost Caddy mints the certificate from an internal CA
 * generated per install, which is in no trust store by design and is not
 * something a test run may install into the machine's. Waiving the trust
 * check is the price; waiving it silently is not. So the run asserts here,
 * once, that the certificate on the port really is Caddy's internal one —
 * if the stack ever came up serving plain HTTP or somebody else's
 * certificate, this fails instead of the suite quietly passing.
 */
async function assertServedByCaddy(): Promise<void> {
  const issuer = await new Promise<string>((resolve, reject) => {
    const socket = tls.connect(
      { host: "localhost", port: HTTPS_PORT, servername: "localhost", rejectUnauthorized: false },
      () => {
        const certificate = socket.getPeerCertificate();
        socket.end();
        resolve(typeof certificate.issuer.CN === "string" ? certificate.issuer.CN : "");
      },
    );
    socket.setTimeout(10_000, () => {
      socket.destroy();
      reject(new Error(`e2e stack: TLS handshake on :${String(HTTPS_PORT)} timed out`));
    });
    socket.on("error", reject);
  });

  if (!issuer.includes(CADDY_INTERNAL_ISSUER)) {
    throw new Error(
      `e2e stack: expected a certificate from Caddy's internal CA on :${String(HTTPS_PORT)}, got issuer ${JSON.stringify(issuer)}`,
    );
  }
}

export function readStackState(): StackState {
  return JSON.parse(readFileSync(STATE_FILE, "utf8")) as StackState;
}

/**
 * Brings the stack up from a clean state and returns what the workers need.
 *
 * Clean matters: the first admin is only bootstrapped into an empty users
 * table, and the login rate limiter lives in the server's memory, so a run
 * that inherited the previous run's database or process would start in a
 * state no test set up. HAMLANEH_E2E_REUSE_STACK=1 skips the recreate for
 * fast local iteration; CI never sets it.
 */
export async function startStack(): Promise<StackState> {
  const reuse = process.env.HAMLANEH_E2E_REUSE_STACK === "1";
  const baseURL = `https://localhost:${String(HTTPS_PORT)}`;

  if (reuse) {
    await waitForHealthy();
    await assertServedByCaddy();
    return readStackState();
  }

  const adminPassword = secret();
  writeEnvFile(adminPassword);
  // -v removes only this project's volumes; the developer's own stack is a
  // different project and is not touched.
  compose(["down", "-v", "--remove-orphans"], { check: false });
  compose(["up", "-d", "--build"]);
  await waitForHealthy();
  await assertServedByCaddy();

  const state: StackState = {
    baseURL,
    // Global setup replaces this with the post-change password.
    admin: { username: "e2eadmin", password: adminPassword },
  };
  return state;
}

export function saveStackState(state: StackState): void {
  mkdirSync(STATE_DIR, { recursive: true });
  writeFileSync(STATE_FILE, `${JSON.stringify(state, null, 2)}\n`, { encoding: "utf8", mode: 0o600 });
}

/** Container logs, for the CI artefact of a failed run. */
export function collectLogs(): string {
  return compose(["logs", "--no-color", "--tail", "400"], { check: false });
}

export function stopStack(): void {
  if (process.env.HAMLANEH_E2E_REUSE_STACK === "1") {
    return;
  }
  compose(["down", "-v", "--remove-orphans"], { check: false });
  rmSync(STATE_DIR, { recursive: true, force: true });
}
