// Command hamlaneh-server runs the Hamlaneh backend HTTP server.
//
// Usage:
//
//	hamlaneh-server              start in server mode on :8080 (PostgreSQL)
//	hamlaneh-server home         start in home mode on 127.0.0.1:8080 (SQLite)
//	hamlaneh-server healthcheck  probe /healthz of a local instance; exit 0 if healthy, 1 otherwise
//	hamlaneh-server --version    print the version this binary was built as
//
// # Server mode
//
// The server needs PostgreSQL, configured via the standard libpq environment
// variables (PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD, PGSSLMODE), and
// applies its schema migrations itself at startup — no manual migrate step.
// HAMLANEH_FILE_URL_KEY (32+ bytes, generated by deploy/install.sh) signs
// the expiring URLs uploaded files are served by; startup stops without it.
// HAMLANEH_AUDIT_KEY (32+ bytes, generated the same way) keys the hash chain
// over the audit log, which is what makes an edited or deleted entry show;
// startup stops without it too.
// HAMLANEH_DATA_DIR is where uploaded bytes are kept (default ./data; the
// compose stack mounts a volume there).
// On a fresh instance (empty users table), HAMLANEH_ADMIN_USERNAME and
// HAMLANEH_ADMIN_PASSWORD (optionally HAMLANEH_ADMIN_LOCALE) create the
// first admin account; once any user exists they are ignored.
// The healthcheck subcommand needs neither a database nor those variables.
//
// Password reset needs an SMTP transport (HAMLANEH_SMTP_HOST and friends)
// and HAMLANEH_PUBLIC_URL to build links from. Setting none of them is a
// supported install: reset is then switched off and says so. Setting them
// half-way is not, and stops startup.
//
// Calls follow the same rule: HAMLANEH_LIVEKIT_API_KEY,
// HAMLANEH_LIVEKIT_API_SECRET and HAMLANEH_LIVEKIT_URL all set turns the
// media plane on; none set is a supported install with calls off and the
// instance document says so; a partial set stops startup.
//
// Single sign-on follows the same rule: HAMLANEH_OIDC_ISSUER,
// HAMLANEH_OIDC_CLIENT_ID and HAMLANEH_OIDC_CLIENT_SECRET (plus the
// optional HAMLANEH_OIDC_PROVIDER_NAME) all set turns it on and needs
// HAMLANEH_PUBLIC_URL for the redirect URI; none set is a supported
// install with SSO off; a partial set stops startup. Provider discovery is
// lazy and retried — an identity provider that is down never stops this
// server booting, and password sign-in is unaffected while it is.
//
// HAMLANEH_ADMIN_ADDR moves the admin surface onto a second listener at that
// address (ADR 015): the dashboard at /admin, everything under
// /api/v1/admin, and the /scim/v2 provisioning surface answer there and
// nowhere else, and the main listener answers 404 for all three. Unset — the
// default and every install before this — keeps all of them where they are.
// The port is a deployment boundary, so a firewall can filter it; it is not
// an authorization decision, and reaching it still faces the same session
// and the same role check.
//
// HAMLANEH_COMPRESS_RESPONSES=1 gzips the embedded web build on the way out.
// It is for home mode, which is a single binary with nothing in front of it:
// the compose stack's Caddy already runs `encode zstd gzip`, so leaving it
// unset there keeps the better encoding and costs this process no CPU. API
// responses are never compressed either way — see
// internal/httpserver/compress.go for why that is a security decision.
//
// The server speaks plain HTTP; TLS termination is the reverse proxy's job.
// It shuts down gracefully on SIGINT/SIGTERM.
//
// # Home mode
//
// `hamlaneh-server home` is PLAN §4's second deployment: one binary, one
// machine, no Docker, no domain and no YAML (ADR 012). It differs from server
// mode in four ways and no others — SQLite instead of PostgreSQL, a loopback
// bind, no calls, and compression on because nothing is in front of it.
//
// Everything lives in one directory, which is therefore the whole backup
// unit: the database (hamlaneh.db and its -wal/-shm siblings), the uploaded
// bytes, and the two keys above, generated on first run instead of by an
// installer. HAMLANEH_DATA_DIR chooses that directory; the default is
// per-user and per-OS (%AppData%\hamlaneh on Windows, ~/Library/Application
// Support/hamlaneh on macOS, ~/.config/hamlaneh on Linux).
//
// HAMLANEH_HOME_ADDR moves the bind off 127.0.0.1:8080, and doing so fails
// closed rather than degrading: sessions are Secure cookies, which browsers
// send over plain HTTP only to localhost, so a LAN-published home instance
// visibly does not sign in until a reverse proxy terminates TLS in front of
// it. HAMLANEH_COMPRESS_RESPONSES=0 turns compression back off.
//
// HAMLANEH_PUBLIC_URL names the origin the browser uses, and defaults to
// http://<the bind address>. Both loopback spellings of it work: on a loopback
// bind the WebSocket handshake accepts localhost, 127.0.0.1 and [::1] on that
// port, because they are one machine and one trust boundary. Any other origin
// is refused exactly as it is in server mode. Startup logs the URL to open.
//
// On a fresh install home mode also creates the first administrator, because
// there is no installer here to set HAMLANEH_ADMIN_USERNAME and
// HAMLANEH_ADMIN_PASSWORD: the account is "admin" with a password generated
// from crypto/rand, printed to the console once and never stored anywhere in
// readable form. Setting those two variables uses them instead. Either way it
// happens only while the users table is empty, so a restart neither prints a
// password again nor mints a second admin.
//
// Home mode has no media server, so the three HAMLANEH_LIVEKIT_* variables
// must be unset; the instance document reports calls off and the UI omits the
// controls, exactly as it does for a server-mode install without LiveKit.
//
// Mode selection is explicit and never falls back in either direction: a
// server-mode instance whose database is unreachable stops, rather than
// quietly opening an empty SQLite file and forking the organization's data.
package main

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/google/uuid"

	"github.com/hamlaneh/hamlaneh/server/internal/audit"
	"github.com/hamlaneh/hamlaneh/server/internal/blobstore"
	"github.com/hamlaneh/hamlaneh/server/internal/bootstrap"
	"github.com/hamlaneh/hamlaneh/server/internal/calls"
	"github.com/hamlaneh/hamlaneh/server/internal/egress"
	"github.com/hamlaneh/hamlaneh/server/internal/filesign"
	"github.com/hamlaneh/hamlaneh/server/internal/healthcheck"
	"github.com/hamlaneh/hamlaneh/server/internal/httpserver"
	"github.com/hamlaneh/hamlaneh/server/internal/linkpreview"
	"github.com/hamlaneh/hamlaneh/server/internal/oidc"
	"github.com/hamlaneh/hamlaneh/server/internal/passwordreset"
	"github.com/hamlaneh/hamlaneh/server/internal/scim"
	"github.com/hamlaneh/hamlaneh/server/internal/storage"
	"github.com/hamlaneh/hamlaneh/server/internal/wsgateway"
)

const (
	listenAddr         = ":8080"
	shutdownTimeout    = 10 * time.Second
	healthcheckTimeout = 5 * time.Second

	// dbStartupTimeout caps how long startup waits for the database to
	// accept connections and for migrations to apply; "docker compose up"
	// starts both containers together and PostgreSQL needs a few seconds.
	dbStartupTimeout = 60 * time.Second
)

// healthcheckURL is where the healthcheck subcommand probes the local
// server. A var, not a const, so tests can point it at a test server.
var healthcheckURL = "http://127.0.0.1:8080/healthz"

// version is what --version prints. The release workflow stamps the tag in
// with -ldflags="-X main.version=$VERSION"; a build that was not released
// says so rather than claiming a version nobody can verify.
//
// It is what an updater reads to know what is installed — deploy/
// verify-release.sh takes it as --installed and refuses a downgrade on it —
// so the output is the tag and nothing else.
var version = "dev"

// stdout is where --version writes. A var so tests can read what it printed.
var stdout io.Writer = os.Stdout

const usage = `usage:
  hamlaneh-server              start in server mode on ` + listenAddr + ` (PostgreSQL)
  hamlaneh-server home         start in home mode on ` + defaultHomeAddr + ` (SQLite)
  hamlaneh-server healthcheck  probe /healthz; exit 0 if healthy, 1 otherwise
  hamlaneh-server --version    print the version this binary was built as`

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "hamlaneh-server: %v\n", err)
		os.Exit(1)
	}
}

// run dispatches on the subcommand in args and returns the process outcome
// as an error (nil means exit 0).
func run(args []string) error {
	switch {
	case len(args) == 0:
		ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
		defer stop()
		return start(ctx, serverMode())
	case args[0] == "home":
		if len(args) > 1 {
			return fmt.Errorf("home takes no arguments\n%s", usage)
		}
		m, err := homeMode()
		if err != nil {
			return err
		}
		ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
		defer stop()
		return start(ctx, m)
	case args[0] == "--version":
		if len(args) > 1 {
			return fmt.Errorf("--version takes no arguments\n%s", usage)
		}
		_, err := fmt.Fprintln(stdout, version)
		return err
	case args[0] == "healthcheck":
		if len(args) > 1 {
			return fmt.Errorf("healthcheck takes no arguments\n%s", usage)
		}
		ctx, cancel := context.WithTimeout(context.Background(), healthcheckTimeout)
		defer cancel()
		return healthcheck.Check(ctx, healthcheckURL)
	default:
		return fmt.Errorf("unknown command %q\n%s", args[0], usage)
	}
}

// start wires the whole server for m and serves until ctx is canceled.
//
// It is ONE function for both modes on purpose (ADR 012): everything below —
// the keys, the bootstrap admin, sessions, authorization, the security
// headers, the audit chain, provisioning — is the same code serving a
// household and an organization, and the only differences are the five fields
// of m. A second wiring function is how the smaller deployment would quietly
// become the weaker one.
func start(ctx context.Context, m mode) error {
	// Home mode's data directory, before anything writes into it. A no-op in
	// server mode, where blobstore owns the directory as it always has.
	if err := m.prepare(); err != nil {
		return err
	}

	// Before the database, because these are answerable without any network
	// at all: the file-URL signing key is the credential every read of an
	// uploaded file is checked against, and the audit chain's key is what
	// makes the log evidence rather than a table of rows. A server that
	// invented either per boot would invalidate every URL it had ever minted
	// and fail to verify everything recorded before the last restart.
	signer, auditChain, err := m.keys()
	if err != nil {
		return err
	}

	// Where uploaded bytes live. Created at startup rather than on the
	// first upload, so a data directory the process cannot write is a
	// failure to start instead of a failure halfway through somebody's
	// file (HAMLANEH_DATA_DIR; compose mounts a volume there).
	blobs, err := blobstore.New(m.dataDir)
	if err != nil {
		return err
	}

	// db rather than store, which is the type below.
	db, err := m.openStore(ctx)
	if err != nil {
		return err
	}
	defer db.Close()

	// The first administrator. Server mode reads the pair install.sh set;
	// home mode, which has no installer, generates the password when nobody
	// supplied one (home.go).
	admin, err := m.firstAdmin()
	if err != nil {
		return err
	}
	created, err := bootstrap.EnsureAdmin(ctx, db, admin.cfg, admin.present)
	if err != nil {
		return err
	}
	// Both conditions, and this is the whole idempotence: minted says the
	// password exists nowhere but this process, created says the account was
	// made by THIS start. A restart fails the second, so the console never
	// shows a credential twice and the account is never made twice.
	if created && admin.minted {
		if err = m.announceFirstAdmin(admin.cfg); err != nil {
			return err
		}
	}

	// A half-configured mail transport, or one with no public URL to build
	// links from, stops startup: reset that silently mints tokens nobody
	// can open is worse than reset that is honestly switched off.
	reset, err := passwordreset.FromEnv(db)
	if err != nil {
		return fmt.Errorf("configure password reset: %w", err)
	}

	// Single sign-on follows the same rule: none of its variables set is
	// a supported install (sso is nil and the endpoints say so), a
	// half-configured set stops startup. Only configuration is checked
	// here — provider discovery is lazy and retried, so an identity
	// provider that is down cannot stop the chat server booting.
	sso, err := oidc.FromEnv(m.publicURL)
	if err != nil {
		return fmt.Errorf("configure single sign-on: %w", err)
	}

	// Calls follow the same rule again: all three LiveKit variables set
	// turns the media plane on, none set is a supported install with
	// calls off and the instance document says so, and a partial set
	// stops startup rather than failing at somebody's first call. Home mode
	// refused any of them before it got here, so media is nil there and the
	// instance document reports calls off (ADR 012).
	media, err := calls.FromEnv()
	if err != nil {
		return fmt.Errorf("configure calls: %w", err)
	}
	// Drains the dispatch queue; the server has stopped accepting
	// requests by the time serve returns.
	defer reset.Close()

	// The realtime gateway. Its Origin check is the CSWSH defense standing
	// in for the CSRF header a browser cannot send on a handshake, so it
	// needs the instance's public origin; without one it allows nothing
	// and every upgrade is refused, which is the right way to fail.
	gateway := wsgateway.New(db, m.publicURL, append(m.gatewayOptions(),
		// Its message frames carry attachments and preview cards, whose
		// URLs are minted per serialization like every other one.
		wsgateway.WithURLSigner(attachmentURLs{signer}))...)
	// Closed before serve returns, because http.Server.Shutdown does not
	// wait for hijacked connections and a WebSocket is one. Without this,
	// shutdown reports success while sockets are still being served.
	//
	// A failure here is logged rather than returned: the process is on
	// its way out, and reporting a shutdown hiccup as the run's outcome
	// would mask whatever actually stopped it.
	defer func() {
		if closeErr := gateway.Close(); closeErr != nil {
			slog.Error("close realtime gateway", "error", closeErr)
		}
	}()

	// Link previews: the guarded egress fetch, off the request path.
	// The gateway is the announcer, so an arriving card reaches every
	// open socket as message_updated (ws-protocol §4).
	previews := linkpreview.New(egress.New(), db, previewBlobs{blobs}, gateway)
	defer previews.Close()

	if m.home {
		// The URL to open, said once and exactly. Reaching the same instance
		// by the other loopback spelling — localhost for 127.0.0.1, or the
		// reverse — works too: the gateway accepts both on this port, because
		// they are one machine and one trust boundary (m.gatewayOptions). The
		// data directory is logged beside it because it is the whole backup
		// unit.
		slog.Info("home mode ready", "open", m.publicURL, "data_dir", m.dataDir)
	}

	srv, adminSrv := httpserver.New(m.addr, offboarding{db, media},
		httpserver.WithPasswordReset(reset),
		httpserver.WithSSO(sso),
		httpserver.WithCalls(media),
		// The same public origin the reset link and the socket's Origin
		// check are built from; here it is what makes an invitation link
		// something an admin can paste into a message.
		httpserver.WithPublicURL(m.publicURL),
		httpserver.WithRealtime(gateway),
		// Response compression. Off unless a server-mode install asked, on
		// unless a home-mode install refused: the compose stack puts Caddy
		// in front and Caddy already compresses, home mode has no proxy at
		// all and is what this is for (internal/httpserver/compress.go).
		httpserver.WithCompression(m.compress),
		// Whether X-Forwarded-For may name the client. Server mode has Caddy
		// in front by construction; home mode has nothing forwarding, so the
		// header there is just something the caller wrote (home.go).
		httpserver.WithTrustedProxy(m.trustsForwardedFor()),
		httpserver.WithFiles(httpserver.Files{
			Signer:      signer,
			Attachments: db,
			Previews:    db,
		}),
		httpserver.WithUploads(blobs, attachmentURLs{signer}),
		httpserver.WithLinkPreviews(previews),
		httpserver.WithAudit(auditRecorder{audit.NewRecorder(auditChain, db)}),
		httpserver.WithAuditChain(auditChain),
		// SCIM provisioning. It needs no configuration and no
		// environment variable: it is off until an administrator mints a
		// token, and unauthenticated until one is presented, so mounting
		// it unconditionally costs a zero-config install nothing.
		//
		// It takes the recorder directly rather than through
		// auditRecorder: the actor of a provisioning action is a
		// credential and never a person, so there is no "nobody" to
		// translate.
		httpserver.WithSCIM(scim.New(offboarding{db, media},
			scim.WithAudit(audit.NewRecorder(auditChain, db)))),
		// The admin surface's own port, off unless an operator named one
		// (ADR 015). It moves the dashboard, /api/v1/admin and /scim/v2
		// off the listener above and onto this one, so a firewall can
		// filter them by port; it moves no authorization decision with
		// them. Home mode never sets it.
		httpserver.WithAdminListener(m.adminAddr),
	)

	srvs := []*http.Server{srv}
	if adminSrv != nil {
		slog.Info("admin surface split onto its own listener", "addr", adminSrv.Addr)
		srvs = append(srvs, adminSrv)
	}
	return serve(ctx, m.addrInUseRemedy(), srvs...)
}

// offboarding is ADR 005's second removal hook: an account that is
// deactivated is ejected from every call it is in.
//
// It hangs off the ONE call both deactivation paths already make. Deactivation
// is UpdateUserAdmin — the admin dashboard's patch and a directory's SCIM
// `active: false` land on the same store method, which takes the advisory
// lock, refuses the change that would leave nobody able to administer the
// instance, and revokes every session family in one transaction; the
// WebSocket gateway's revocation sweep then closes the sockets (ADR 004,
// scim.md §5). This wrapper extends that path from sockets to calls rather
// than opening a second one, which is why it is a decorator here and not a
// call added to each of the two handlers: a hook only one of them remembered
// would be an offboarding that half works.
//
// Only a COMMITTED deactivation ejects. A refused change (last admin) and a
// reactivation both leave calls alone, and the ejection itself is background
// work that cannot fail the request — see calls.Service.EjectEverywhere.
type offboarding struct {
	store
	calls *calls.Service
}

// store is what this command needs from persistent storage: everything the
// HTTP surface reads and writes, plus the provisioning surface's own reads,
// because offboarding decorates one method and is handed to both.
//
// It is an interface rather than *storage.Store so that home mode's SQLite
// driver can be wired here too (ADR 012): the seam between the server and a
// driver is the consumer's interface, and this is the consumer.
type store interface {
	// The interfaces the consumers this command wires already declare for
	// themselves. Nothing is invented here: this is the union of what is
	// handed to whom below, and the compiler is what checks a driver
	// against it.
	httpserver.Store
	scim.Store
	bootstrap.Store
	passwordreset.Store
	linkpreview.Store

	// The residue: two reads the files origin needs that internal/httpserver
	// names only through unexported interfaces (attachmentReader,
	// previewImageReader in files_origin.go). Exporting those would widen
	// that package's API to satisfy this one declaration.
	AttachmentByID(ctx context.Context, id uuid.UUID) (storage.Attachment, error)
	LinkPreviewImageExists(ctx context.Context, blobID uuid.UUID) (bool, error)

	// Releases the driver's connections at shutdown. No consumer interface
	// names it — a handler has no business closing the database — but the
	// process that opened it does.
	Close()
}

func (o offboarding) UpdateUserAdmin(ctx context.Context, userID uuid.UUID, upd storage.AdminUserUpdate) (storage.User, error) {
	user, err := o.store.UpdateUserAdmin(ctx, userID, upd)
	if err == nil && !user.IsActive {
		o.calls.EjectEverywhere(ctx, user.ID)
	}
	return user, err
}

// previewBlobs adapts the blob store to the enricher's one-shot write. A
// preview derivative is small by construction (bounded at ingest), so the
// buffered []byte the enricher hands over costs nothing worth streaming.
type previewBlobs struct{ store *blobstore.Store }

func (p previewBlobs) WriteBlob(_ context.Context, id uuid.UUID, data []byte) error {
	f, err := p.store.Create(id, blobstore.Original)
	if err != nil {
		return err
	}
	if _, err = f.Write(data); err != nil {
		closeErr := f.Close()
		_ = closeErr
		return err
	}
	return f.Close()
}

// auditRecorder is the wiring between the two halves of the audit log: the
// handlers, which describe what happened in their own terms, and the
// recorder, which seals and stores it. It lives here for the reason
// attachmentURLs does — neither package should have to know the other's
// shape, and internal/audit must not import the HTTP layer.
//
// The two shapes differ in exactly one way: a handler spells "nobody" as
// the zero UUID, and the log stores it as a null column. This is where that
// translation happens, once, rather than at every call site.
type auditRecorder struct {
	recorder *audit.Recorder
}

func (a auditRecorder) Record(ctx context.Context, ev httpserver.AuditEvent) {
	rec := audit.Record{
		Action:      ev.Action,
		TargetLabel: ev.TargetLabel,
		Detail:      ev.Detail,
		IP:          ev.IP,
	}
	if ev.ActorID != uuid.Nil {
		actorID := ev.ActorID
		rec.ActorID = &actorID
	}
	if ev.TargetID != uuid.Nil {
		targetID := ev.TargetID
		rec.TargetID = &targetID
	}
	a.recorder.Record(ctx, rec)
}

// attachmentURLs is the wiring between the two halves of a file's URL: the
// signer, which knows how to sign one, and the API layer, which asks for a
// pair per serialized attachment. It lives here because it is a wiring
// decision — neither package should have to know the other's shape.
type attachmentURLs struct {
	signer *filesign.Signer
}

func (a attachmentURLs) AttachmentURLs(id uuid.UUID, hasThumbnail bool) (string, *string) {
	fileURL := a.signer.FileURL(id, blobstore.Original)
	if !hasThumbnail {
		return fileURL, nil
	}
	thumbnailURL := a.signer.FileURL(id, blobstore.Thumbnail)
	return fileURL, &thumbnailURL
}

// openStorage connects to PostgreSQL (configured via the standard libpq
// environment variables) and applies pending schema migrations, waiting up
// to dbStartupTimeout for a database that is still starting.
func openStorage(ctx context.Context) (*storage.Store, error) {
	slog.Info("connecting to database and applying migrations")
	dbCtx, cancel := context.WithTimeout(ctx, dbStartupTimeout)
	defer cancel()

	store, err := storage.Open(dbCtx, "")
	if err != nil {
		return nil, fmt.Errorf("open storage: %w", err)
	}
	slog.Info("database ready")
	return store, nil
}

// isAddrInUse reports whether a listen failed because something already holds
// the port.
//
// It checks two things rather than one because syscall.EADDRINUSE is NOT what
// Windows returns: there the error is WSAEADDRINUSE, numerically 10048, which
// errors.Is(err, syscall.EADDRINUSE) does not match and which the syscall
// package does not export a constant for. Home mode's whole point is running
// on a household machine, and on Windows that machine usually has Docker
// Desktop already holding :8080 -- so the platform where this matters most is
// exactly the one the portable-looking check silently fails on. A test on a
// really-taken port is what caught it, and is what keeps it caught.
func isAddrInUse(err error) bool {
	if errors.Is(err, syscall.EADDRINUSE) {
		return true
	}
	const wsaeAddrInUse = 10048
	var errno syscall.Errno
	return errors.As(err, &errno) && uintptr(errno) == wsaeAddrInUse
}

// serve runs every server in srvs until ctx is canceled, then shuts them all
// down gracefully within one shutdownTimeout. There are two only when the
// admin surface has its own port (ADR 015); the second is not optional once
// it exists, so the first listen failure stops the process rather than
// leaving half an instance up.
//
// addrInUse is what to tell the operator when the port is taken, and it is a
// parameter because the way out differs by mode: home mode has an environment
// variable, a compose deployment has a port mapping to edit instead.
func serve(ctx context.Context, addrInUse string, srvs ...*http.Server) error {
	serveErr := make(chan error, len(srvs))
	for _, srv := range srvs {
		go func() {
			serveErr <- srv.ListenAndServe()
		}()
		slog.Info("hamlaneh-server listening", "addr", srv.Addr)
	}

	select {
	case err := <-serveErr:
		// ListenAndServe failed before any shutdown was requested. The
		// common one by far is the address already being in use, and on a
		// household machine the usual holder of :8080 is Docker Desktop --
		// so the person most likely to hit it is the one least likely to
		// know that a bind error has a remedy at all.
		if isAddrInUse(err) {
			return fmt.Errorf("serve: %w (%s)", err, addrInUse)
		}
		return fmt.Errorf("serve: %w", err)
	case <-ctx.Done():
	}

	slog.Info("shutting down")
	shutdownCtx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()
	for _, srv := range srvs {
		if err := srv.Shutdown(shutdownCtx); err != nil {
			return fmt.Errorf("shutdown: %w", err)
		}
	}

	for range srvs {
		if err := <-serveErr; err != nil && !errors.Is(err, http.ErrServerClosed) {
			return fmt.Errorf("serve: %w", err)
		}
	}
	return nil
}
