// Command hamlaneh-server runs the Hamlaneh backend HTTP server.
//
// Usage:
//
//	hamlaneh-server              start the server on :8080
//	hamlaneh-server healthcheck  probe /healthz of a local instance; exit 0 if healthy, 1 otherwise
//
// The server needs PostgreSQL, configured via the standard libpq environment
// variables (PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD, PGSSLMODE), and
// applies its schema migrations itself at startup — no manual migrate step.
// HAMLANEH_FILE_URL_KEY (32+ bytes, generated by deploy/install.sh) signs
// the expiring URLs uploaded files are served by; startup stops without it.
// HAMLANEH_AUDIT_KEY (32+ bytes, generated the same way) keys the hash chain
// over the audit log, which is what makes an edited or deleted entry show;
// startup stops without it too.
// HAMLANEH_DATA_DIR is where uploaded bytes are kept (default ./data; the
// compose stack mounts a volume there).
// On a fresh instance (empty users table), HAMLANEH_ADMIN_USERNAME and
// HAMLANEH_ADMIN_PASSWORD (optionally HAMLANEH_ADMIN_LOCALE) create the
// first admin account; once any user exists they are ignored.
// The healthcheck subcommand needs neither a database nor those variables.
//
// Password reset needs an SMTP transport (HAMLANEH_SMTP_HOST and friends)
// and HAMLANEH_PUBLIC_URL to build links from. Setting none of them is a
// supported install: reset is then switched off and says so. Setting them
// half-way is not, and stops startup.
//
// Single sign-on follows the same rule: HAMLANEH_OIDC_ISSUER,
// HAMLANEH_OIDC_CLIENT_ID and HAMLANEH_OIDC_CLIENT_SECRET (plus the
// optional HAMLANEH_OIDC_PROVIDER_NAME) all set turns it on and needs
// HAMLANEH_PUBLIC_URL for the redirect URI; none set is a supported
// install with SSO off; a partial set stops startup. Provider discovery is
// lazy and retried — an identity provider that is down never stops this
// server booting, and password sign-in is unaffected while it is.
//
// The server speaks plain HTTP; TLS termination is the reverse proxy's job.
// It shuts down gracefully on SIGINT/SIGTERM.
package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/google/uuid"

	"github.com/hamlaneh/hamlaneh/server/internal/audit"
	"github.com/hamlaneh/hamlaneh/server/internal/blobstore"
	"github.com/hamlaneh/hamlaneh/server/internal/bootstrap"
	"github.com/hamlaneh/hamlaneh/server/internal/egress"
	"github.com/hamlaneh/hamlaneh/server/internal/filesign"
	"github.com/hamlaneh/hamlaneh/server/internal/healthcheck"
	"github.com/hamlaneh/hamlaneh/server/internal/httpserver"
	"github.com/hamlaneh/hamlaneh/server/internal/linkpreview"
	"github.com/hamlaneh/hamlaneh/server/internal/oidc"
	"github.com/hamlaneh/hamlaneh/server/internal/passwordreset"
	"github.com/hamlaneh/hamlaneh/server/internal/scim"
	"github.com/hamlaneh/hamlaneh/server/internal/storage"
	"github.com/hamlaneh/hamlaneh/server/internal/wsgateway"
)

const (
	listenAddr         = ":8080"
	shutdownTimeout    = 10 * time.Second
	healthcheckTimeout = 5 * time.Second

	// dbStartupTimeout caps how long startup waits for the database to
	// accept connections and for migrations to apply; "docker compose up"
	// starts both containers together and PostgreSQL needs a few seconds.
	dbStartupTimeout = 60 * time.Second
)

// healthcheckURL is where the healthcheck subcommand probes the local
// server. A var, not a const, so tests can point it at a test server.
var healthcheckURL = "http://127.0.0.1:8080/healthz"

const usage = `usage:
  hamlaneh-server              start the server on ` + listenAddr + `
  hamlaneh-server healthcheck  probe /healthz; exit 0 if healthy, 1 otherwise`

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "hamlaneh-server: %v\n", err)
		os.Exit(1)
	}
}

// run dispatches on the subcommand in args and returns the process outcome
// as an error (nil means exit 0).
func run(args []string) error {
	switch {
	case len(args) == 0:
		ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
		defer stop()

		// Before the database, because this one is answerable without any
		// network at all: the file-URL signing key is the credential every
		// read of an uploaded file is checked against, and a server that
		// invented one per boot would invalidate every URL it had ever
		// minted on every restart.
		signer, err := filesign.FromEnv()
		if err != nil {
			return err
		}

		// The audit chain's key, for the same reason and at the same point:
		// it is what makes the log evidence rather than a table of rows, a
		// key invented per boot would fail to verify everything recorded
		// before the last restart, and a built-in default would let anybody
		// who knows it rewrite the chain and re-seal it.
		auditChain, err := audit.FromEnv()
		if err != nil {
			return err
		}

		// Where uploaded bytes live. Created at startup rather than on the
		// first upload, so a data directory the process cannot write is a
		// failure to start instead of a failure halfway through somebody's
		// file (HAMLANEH_DATA_DIR; compose mounts a volume there).
		blobs, err := blobstore.FromEnv()
		if err != nil {
			return err
		}

		store, err := openStorage(ctx)
		if err != nil {
			return err
		}
		defer store.Close()

		adminCfg, present := bootstrap.AdminFromEnv()
		if err = bootstrap.EnsureAdmin(ctx, store, adminCfg, present); err != nil {
			return err
		}

		// A half-configured mail transport, or one with no public URL to build
		// links from, stops startup: reset that silently mints tokens nobody
		// can open is worse than reset that is honestly switched off.
		reset, err := passwordreset.FromEnv(store)
		if err != nil {
			return fmt.Errorf("configure password reset: %w", err)
		}

		// Single sign-on follows the same rule: none of its variables set is
		// a supported install (sso is nil and the endpoints say so), a
		// half-configured set stops startup. Only configuration is checked
		// here — provider discovery is lazy and retried, so an identity
		// provider that is down cannot stop the chat server booting.
		sso, err := oidc.FromEnv(os.Getenv(passwordreset.EnvPublicURL))
		if err != nil {
			return fmt.Errorf("configure single sign-on: %w", err)
		}
		// Drains the dispatch queue; the server has stopped accepting
		// requests by the time serve returns.
		defer reset.Close()

		// The realtime gateway. Its Origin check is the CSWSH defense standing
		// in for the CSRF header a browser cannot send on a handshake, so it
		// needs the instance's public origin; without one it allows nothing
		// and every upgrade is refused, which is the right way to fail.
		gateway := wsgateway.New(store, os.Getenv(passwordreset.EnvPublicURL),
			// Its message frames carry attachments and preview cards, whose
			// URLs are minted per serialization like every other one.
			wsgateway.WithURLSigner(attachmentURLs{signer}))
		// Closed before serve returns, because http.Server.Shutdown does not
		// wait for hijacked connections and a WebSocket is one. Without this,
		// shutdown reports success while sockets are still being served.
		//
		// A failure here is logged rather than returned: the process is on
		// its way out, and reporting a shutdown hiccup as the run's outcome
		// would mask whatever actually stopped it.
		defer func() {
			if closeErr := gateway.Close(); closeErr != nil {
				slog.Error("close realtime gateway", "error", closeErr)
			}
		}()

		// Link previews: the guarded egress fetch, off the request path.
		// The gateway is the announcer, so an arriving card reaches every
		// open socket as message_updated (ws-protocol §4).
		previews := linkpreview.New(egress.New(), store, previewBlobs{blobs}, gateway)
		defer previews.Close()

		return serve(ctx, httpserver.New(listenAddr, store,
			httpserver.WithPasswordReset(reset),
			httpserver.WithSSO(sso),
			// The same public origin the reset link and the socket's Origin
			// check are built from; here it is what makes an invitation link
			// something an admin can paste into a message.
			httpserver.WithPublicURL(os.Getenv(passwordreset.EnvPublicURL)),
			httpserver.WithRealtime(gateway),
			httpserver.WithFiles(httpserver.Files{
				Signer:      signer,
				Attachments: store,
				Previews:    store,
			}),
			httpserver.WithUploads(blobs, attachmentURLs{signer}),
			httpserver.WithLinkPreviews(previews),
			httpserver.WithAudit(auditRecorder{audit.NewRecorder(auditChain, store)}),
			httpserver.WithAuditChain(auditChain),
			// SCIM provisioning. It needs no configuration and no
			// environment variable: it is off until an administrator mints a
			// token, and unauthenticated until one is presented, so mounting
			// it unconditionally costs a zero-config install nothing.
			//
			// It takes the recorder directly rather than through
			// auditRecorder: the actor of a provisioning action is a
			// credential and never a person, so there is no "nobody" to
			// translate.
			httpserver.WithSCIM(scim.New(store,
				scim.WithAudit(audit.NewRecorder(auditChain, store)))),
		))
	case args[0] == "healthcheck":
		if len(args) > 1 {
			return fmt.Errorf("healthcheck takes no arguments\n%s", usage)
		}
		ctx, cancel := context.WithTimeout(context.Background(), healthcheckTimeout)
		defer cancel()
		return healthcheck.Check(ctx, healthcheckURL)
	default:
		return fmt.Errorf("unknown command %q\n%s", args[0], usage)
	}
}

// previewBlobs adapts the blob store to the enricher's one-shot write. A
// preview derivative is small by construction (bounded at ingest), so the
// buffered []byte the enricher hands over costs nothing worth streaming.
type previewBlobs struct{ store *blobstore.Store }

func (p previewBlobs) WriteBlob(_ context.Context, id uuid.UUID, data []byte) error {
	f, err := p.store.Create(id, blobstore.Original)
	if err != nil {
		return err
	}
	if _, err = f.Write(data); err != nil {
		closeErr := f.Close()
		_ = closeErr
		return err
	}
	return f.Close()
}

// auditRecorder is the wiring between the two halves of the audit log: the
// handlers, which describe what happened in their own terms, and the
// recorder, which seals and stores it. It lives here for the reason
// attachmentURLs does — neither package should have to know the other's
// shape, and internal/audit must not import the HTTP layer.
//
// The two shapes differ in exactly one way: a handler spells "nobody" as
// the zero UUID, and the log stores it as a null column. This is where that
// translation happens, once, rather than at every call site.
type auditRecorder struct {
	recorder *audit.Recorder
}

func (a auditRecorder) Record(ctx context.Context, ev httpserver.AuditEvent) {
	rec := audit.Record{
		Action:      ev.Action,
		TargetLabel: ev.TargetLabel,
		Detail:      ev.Detail,
		IP:          ev.IP,
	}
	if ev.ActorID != uuid.Nil {
		actorID := ev.ActorID
		rec.ActorID = &actorID
	}
	if ev.TargetID != uuid.Nil {
		targetID := ev.TargetID
		rec.TargetID = &targetID
	}
	a.recorder.Record(ctx, rec)
}

// attachmentURLs is the wiring between the two halves of a file's URL: the
// signer, which knows how to sign one, and the API layer, which asks for a
// pair per serialized attachment. It lives here because it is a wiring
// decision — neither package should have to know the other's shape.
type attachmentURLs struct {
	signer *filesign.Signer
}

func (a attachmentURLs) AttachmentURLs(id uuid.UUID, hasThumbnail bool) (string, *string) {
	fileURL := a.signer.FileURL(id, blobstore.Original)
	if !hasThumbnail {
		return fileURL, nil
	}
	thumbnailURL := a.signer.FileURL(id, blobstore.Thumbnail)
	return fileURL, &thumbnailURL
}

// openStorage connects to PostgreSQL (configured via the standard libpq
// environment variables) and applies pending schema migrations, waiting up
// to dbStartupTimeout for a database that is still starting.
func openStorage(ctx context.Context) (*storage.Store, error) {
	slog.Info("connecting to database and applying migrations")
	dbCtx, cancel := context.WithTimeout(ctx, dbStartupTimeout)
	defer cancel()

	store, err := storage.Open(dbCtx, "")
	if err != nil {
		return nil, fmt.Errorf("open storage: %w", err)
	}
	slog.Info("database ready")
	return store, nil
}

// serve runs srv until ctx is canceled, then shuts it down gracefully within
// shutdownTimeout.
func serve(ctx context.Context, srv *http.Server) error {
	serveErr := make(chan error, 1)
	go func() {
		serveErr <- srv.ListenAndServe()
	}()
	slog.Info("hamlaneh-server listening", "addr", srv.Addr)

	select {
	case err := <-serveErr:
		// ListenAndServe failed before any shutdown was requested
		// (e.g. the address is already in use).
		return fmt.Errorf("serve: %w", err)
	case <-ctx.Done():
	}

	slog.Info("shutting down")
	shutdownCtx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		return fmt.Errorf("shutdown: %w", err)
	}

	if err := <-serveErr; err != nil && !errors.Is(err, http.ErrServerClosed) {
		return fmt.Errorf("serve: %w", err)
	}
	return nil
}
