import { rm } from "node:fs/promises";
import path from "node:path";

import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import type { Plugin } from "vite";
import { defineConfig } from "vitest/config";

/**
 * public/mockServiceWorker.js (generated by `msw init`, committed) must be
 * servable in dev so `VITE_API_MOCK=1 npm run dev` works, but it is dev-only
 * tooling — drop it from production build output. The app bundle never
 * registers it in production either (see the guard in src/main.tsx).
 */
function dropMockServiceWorker(): Plugin {
  let outDir = "";
  return {
    name: "hamlaneh:drop-mock-service-worker",
    apply: "build",
    configResolved(config) {
      outDir = path.resolve(config.root, config.build.outDir);
    },
    async closeBundle() {
      await rm(path.join(outDir, "mockServiceWorker.js"), { force: true });
    },
  };
}

export default defineConfig({
  plugins: [react(), tailwindcss(), dropMockServiceWorker()],
  test: {
    environment: "jsdom",
    // worker_threads instead of child processes: faster for this suite and
    // works in sandboxed environments where process spawning is restricted.
    pool: "threads",
    setupFiles: ["./src/test/setup.ts"],
    css: false,
  },
});
